title: "Prasad Speaks"

author:
  name: iamprasadraju
  email: prasadrajuhere@gmail.com

description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

# Minima requires the following plugins:
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations:
    - import

minima:
  # Minima skin selection. Available skins are:
  #   * classic            Default, light color scheme.
  #   * dark               Dark variant of the classic skin.
  #   * auto               Adaptive skin based on the classic and dark skins.
  #   * solarized-light    Light variant of solarized color scheme.
  #   * solarized-dark     Dark variant of solarized color scheme.
  #   * solarized          Adaptive skin for solarized color scheme skins.
  skin: auto
  
  nav_pages:
    - project.md
    - research.md
    - blogs.md
    - notes.md

  # Show Excerpts for posts or not
  show_excerpts: false

  # Default date format
  date_format: "%b-%d-%Y"
  
  # Social links for your site
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/iamprasadraju"
    - title: Jekyll at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/jekyllrb"
  
  # Hide the site feed link in the footer
  hide_site_feed_link: true

collections:
  notes:
    output: true
    permalink: /notes/:title/
  blogs:
    output: true
    permalink: /blogs/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Disqus Comments
disqus:
  shortname: "portfolio-wp5t2dawju"

